"""empty message

Revision ID: 23b93c8f54ab
Revises: 065b24deaaa4
Create Date: 2017-05-21 02:27:17.081838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23b93c8f54ab'
down_revision = '065b24deaaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_contact_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_contact_users')
    # ### end Alembic commands ###
